// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf-_gfwdkYpkIj2aTwlWAOT9TGHAhN4Mc',
    appId: '1:446932438032:web:5389b1b97fb352d33c4e95',
    messagingSenderId: '446932438032',
    projectId: 'taher-jewellery',
    authDomain: 'taher-jewellery.firebaseapp.com',
    storageBucket: 'taher-jewellery.appspot.com',
    measurementId: 'G-ZST6CL30XX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiwGgKWCbVuFcFX-OrqogA_pDF8-68DmA',
    appId: '1:446932438032:android:9ab82edd85c1ef7a3c4e95',
    messagingSenderId: '446932438032',
    projectId: 'taher-jewellery',
    storageBucket: 'taher-jewellery.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdSo3Ol-GjXv3-PP9ZMAjWnmOo4t5QsxE',
    appId: '1:446932438032:ios:92b845fc236bd91e3c4e95',
    messagingSenderId: '446932438032',
    projectId: 'taher-jewellery',
    storageBucket: 'taher-jewellery.appspot.com',
    iosClientId: '446932438032-a0fo39jnt57v2mc6tkid45tsld5lmdcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.loadFirebaseImages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdSo3Ol-GjXv3-PP9ZMAjWnmOo4t5QsxE',
    appId: '1:446932438032:ios:1d8473ab0f766f423c4e95',
    messagingSenderId: '446932438032',
    projectId: 'taher-jewellery',
    storageBucket: 'taher-jewellery.appspot.com',
    iosClientId: '446932438032-1upaq2ilrm9jd4j0049utktvsqq8b14i.apps.googleusercontent.com',
    iosBundleId: 'com.example.loadFirebaseImages.RunnerTests',
  );
}
